In [2]:
import numpy as np

In [3]:
# 1. Создать квадратную матрицу из случайных вещественных чисел (2, 4) размера 10.
matrix1 = np.random.uniform(2, 4, (10, 10))
matrix1

array([[2.53167117, 3.73036428, 2.64515539, 2.72671368, 2.3654165 ,
        3.99777481, 2.52150325, 3.42809527, 2.20071404, 2.0916422 ],
       [2.2023763 , 3.3094113 , 3.88599496, 3.01507633, 3.54803821,
        3.09331085, 2.00267244, 3.02924845, 3.0710393 , 2.28446339],
       [2.32881582, 2.33271707, 3.99524412, 2.31435763, 3.42230306,
        3.78713196, 3.27240675, 3.97897492, 2.07902523, 2.28640629],
       [3.02812733, 3.36780875, 2.29959173, 3.78239588, 2.88695236,
        3.3904126 , 2.61187483, 2.36142731, 2.41083492, 2.60336584],
       [2.55842691, 3.54159755, 2.03449481, 3.87756909, 2.78560206,
        3.46797766, 2.21663439, 3.04765949, 3.09368237, 2.00709996],
       [3.49835339, 3.95525323, 2.23202897, 3.31287833, 3.93466585,
        2.72137496, 3.49315109, 3.35147097, 3.32211736, 3.4301768 ],
       [2.30637316, 2.57211609, 2.81496791, 2.01031113, 2.37625117,
        2.22690654, 3.44188589, 2.41888307, 3.60829296, 2.57990386],
       [2.45804954, 2.57686702, 2.4163300

In [4]:
# Найти скалярное произведение 4 строки на 5 столбец. Использовать срезы матриц.
row_4 = matrix1[3, :]  # 4-я строка (индекс 3, т.к. индексация с 0)
col_5 = matrix1[:, 4]  # 5-й столбец (индекс 4)
row_4, col_5

(array([3.02812733, 3.36780875, 2.29959173, 3.78239588, 2.88695236,
        3.3904126 , 2.61187483, 2.36142731, 2.41083492, 2.60336584]),
 array([2.3654165 , 3.54803821, 3.42230306, 2.88695236, 2.78560206,
        3.93466585, 2.37625117, 3.12633503, 3.67851078, 2.54734502]))

In [5]:
scalar_product_1 = np.dot(row_4, col_5)
scalar_product_1

88.37247095965523

In [6]:
# 2. Создать две матрицы из случайных целых чисел [2, 7) подходящего размера.
matrix2 = np.random.randint(2, 7, (3, 3))
matrix3 = np.random.randint(2, 7, (3, 3))

In [7]:
# Скалярный алгоритм умножения матриц.
def scalar_multiplication(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Векторный алгоритм.
def vector_multiplication(A, B):
    return np.dot(A, B)

In [8]:
result_scalar = scalar_multiplication(matrix2, matrix3)
result_vector = vector_multiplication(matrix2, matrix3)
result_np_dot = np.dot(matrix2, matrix3)

print("\nПроизведение матриц (скалярный алгоритм):\n", result_scalar)
print("\nПроизведение матриц (векторный алгоритм):\n", result_vector)
print("\nПроизведение матриц (np.dot):\n", result_np_dot)


Произведение матриц (скалярный алгоритм):
 [[55. 38. 36.]
 [75. 60. 48.]
 [70. 46. 44.]]

Произведение матриц (векторный алгоритм):
 [[55 38 36]
 [75 60 48]
 [70 46 44]]

Произведение матриц (np.dot):
 [[55 38 36]
 [75 60 48]
 [70 46 44]]


In [9]:
# 3. Создать вектор-строку 1x10 из случайных целых чисел.
vector = np.random.randint(1, 10, 10)

In [10]:
# Вычислить норму ‖x‖2 самостоятельно написанной функцией.
def norm_2(vector):
    return np.sqrt(np.sum(vector**2))

norm_2_custom = norm_2(vector)
norm_2_np = np.linalg.norm(vector)

print("\nНорма вектора ‖x‖2 (собственная реализация):", norm_2_custom)
print("Норма вектора ‖x‖2 (np.linalg.norm):", norm_2_np)


Норма вектора ‖x‖2 (собственная реализация): 17.4928556845359
Норма вектора ‖x‖2 (np.linalg.norm): 17.4928556845359


In [11]:
# 4. Создать матрицу из случайных целых чисел.
matrix4 = np.random.randint(1, 10, (5, 5))

# Найти норму матрицы ‖A‖∞ (максимальная сумма по строкам).
def norm_inf(matrix):
    return np.max(np.sum(np.abs(matrix), axis=1))

norm_inf_custom = norm_inf(matrix4)
norm_inf_np = np.linalg.norm(matrix4, ord=np.inf)

print("\nНорма матрицы ‖A‖∞ (собственная реализация):", norm_inf_custom)
print("Норма матрицы ‖A‖∞ (np.linalg.norm):", norm_inf_np)


Норма матрицы ‖A‖∞ (собственная реализация): 24
Норма матрицы ‖A‖∞ (np.linalg.norm): 24.0


In [12]:
# 5. Найти отражение Хаусхолдера для вектора, которое обнуляет его координаты с 6 по 10.
def householder_reflection(vector):
    v = vector[5:]  # часть вектора с 6 по 10 элемент
    e = np.zeros_like(v)
    e[0] = np.linalg.norm(v)
    u = v - e
    u = u / np.linalg.norm(u)  # нормализуем вектор

    H = np.eye(len(v)) - 2 * np.outer(u, u)
    v_new = H @ v
    vector[5:] = v_new
    return vector

vector_reflected = householder_reflection(vector.copy())
print("\nОтражение Хаусхолдера для вектора:\n", vector_reflected)


Отражение Хаусхолдера для вектора:
 [ 2  5  6  9  5 11  0  0  0  0]


In [16]:
# 6. LU-разложение самостоятельно написанной функцией.
def lu_decomposition(matrix):
    n = matrix.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        for j in range(i, n):
            U[i, j] = matrix[i, j] - L[i, :i] @ U[:i, j]
        L[i, i] = 1
        for j in range(i + 1, n):
            L[j, i] = (matrix[j, i] - L[j, :i] @ U[:i, i]) / U[i, i]

    return L, U

L, U = lu_decomposition(matrix4)
LU_multiplied = np.dot(L, U)

print("\nLU-разложение:")
print("L:\n", L)
print("U:\n", U)
print("Проверка LU-разложения (L*U):\n", LU_multiplied)
print(matrix4)


LU-разложение:
L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 1.25        1.          0.          0.          0.        ]
 [ 1.75        1.5         1.          0.          0.        ]
 [ 0.25       -0.         -2.          1.          0.        ]
 [ 0.75        1.         -2.28571429  0.9025974   1.        ]]
U:
 [[  4.           8.           6.           5.           1.        ]
 [  0.          -4.          -4.5         -1.25         0.75      ]
 [  0.           0.          -1.75        -5.875        3.125     ]
 [  0.           0.           0.         -11.           7.        ]
 [  0.           0.           0.           0.           2.32467532]]
Проверка LU-разложения (L*U):
 [[4. 8. 6. 5. 1.]
 [5. 6. 3. 5. 2.]
 [7. 8. 2. 1. 6.]
 [1. 2. 5. 2. 1.]
 [3. 2. 4. 6. 3.]]
[[4 8 6 5 1]
 [5 6 3 5 2]
 [7 8 2 1 6]
 [1 2 5 2 1]
 [3 2 4 6 3]]


In [17]:
# 7. QR-разложение всеми методами и проверка.
# Метод Грама-Шмидта
def qr_gram_schmidt(matrix):
    n = matrix.shape[0]
    Q = np.zeros_like(matrix, dtype=float)
    R = np.zeros((n, n), dtype=float)

    for j in range(n):
        v = matrix[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], matrix[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

Q_gs, R_gs = qr_gram_schmidt(matrix4)
QR_multiplied_gs = np.dot(Q_gs, R_gs)

print("\nQR-разложение методом Грама-Шмидта:")
print("Q:\n", Q_gs)
print("R:\n", R_gs)
print("Проверка QR-разложения (Q*R):\n", QR_multiplied_gs)

# QR-разложение через np.linalg.qr
Q_np, R_np = np.linalg.qr(matrix4)
QR_multiplied_np = np.dot(Q_np, R_np)

print("\nQR-разложение (np.linalg.qr):")
print("Q:\n", Q_np)
print("R:\n", R_np)
print("Проверка QR-разложения (Q*R):\n", QR_multiplied_np)



QR-разложение методом Грама-Шмидта:
Q:
 [[ 0.4         0.81348157  0.10177787  0.24107902  0.33131541]
 [ 0.5        -0.08244746 -0.04213385  0.46359463 -0.72560814]
 [ 0.7        -0.22535638 -0.39288447 -0.51361499  0.20262265]
 [ 0.1         0.20337039  0.65936739 -0.60746789 -0.380602  ]
 [ 0.3        -0.48918824  0.63146056  0.30682785  0.42167416]]
R:
 [[10.         12.6         7.          7.2         6.6       ]
 [ 0.          3.63868108  3.24293329  0.90142552 -1.96774596]
 [ 0.          0.          5.52117593  5.01283377  0.21395241]
 [ 0.          0.          0.          3.6357846  -1.60040598]
 [ 0.          0.          0.          0.          0.98025552]]
Проверка QR-разложения (Q*R):
 [[4. 8. 6. 5. 1.]
 [5. 6. 3. 5. 2.]
 [7. 8. 2. 1. 6.]
 [1. 2. 5. 2. 1.]
 [3. 2. 4. 6. 3.]]

QR-разложение (np.linalg.qr):
Q:
 [[-0.4         0.81348157  0.10177787  0.24107902  0.33131541]
 [-0.5        -0.08244746 -0.04213385  0.46359463 -0.72560814]
 [-0.7        -0.22535638 -0.39288447 -0