In [2]:
import numpy as np
import pandas as pd
from scipy.linalg import lu

In [3]:
A = np.tril(np.random.rand(5, 5) * 10)  # Нижнетреугольная матрица
B = np.random.rand(5) * 10  # Вектор B
X = np.linalg.solve(A, B)

print("Задача 1: Решение системы AX = B с нижнетреугольной матрицей")
print("Матрица A:\n", A)
print("Вектор B:\n", B)
print("Решение X:\n", X)

Задача 1: Решение системы AX = B с нижнетреугольной матрицей
Матрица A:
 [[9.47367836 0.         0.         0.         0.        ]
 [3.32095489 1.59127583 0.         0.         0.        ]
 [1.81939995 6.81088867 8.07330456 0.         0.        ]
 [5.70590246 0.77888455 7.8308823  9.25726431 0.        ]
 [4.63024917 2.62335737 1.83709715 6.17749363 4.66743734]]
Вектор B:
 [5.18834814 4.51591377 6.43526598 6.95119389 3.71114167]
Решение X:
 [ 0.54765931  1.6949682  -0.75624362  0.9104389  -1.60818489]


In [4]:
A = np.array([
    [8.2, -3.2, 14.2, 14.8],
    [5.6, -12, 15, -6.4],
    [5.7, 3.6, -12.4, -2.3],
    [6.8, 13.2, -6.3, -8.7]
])
B = np.array([-8.4, 4.5, 3.3, 14.3])
    
P, L, U = lu(A)
Y = np.linalg.solve(L, np.dot(P, B))
X = np.linalg.solve(U, Y)
    
print("Задача 2: Решение системы методом LU-разложения")
print("Решение X:\n", X)

Задача 2: Решение системы методом LU-разложения
Решение X:
 [ 0.34261045  0.44394439  0.17387099 -0.82822646]


In [5]:
# Задача 3: Решение системы QR-разложением методом Грама-Шмидта
def gramschmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R

In [6]:
A = np.array([
    [8.2, -3.2, 14.2, 14.8],
    [5.6, -12, 15, -6.4],
    [5.7, 3.6, -12.4, -2.3],
    [6.8, 13.2, -6.3, -8.7]
])
B = np.array([-8.4, 4.5, 3.3, 14.3])
Q, R = gramschmidt(A)
Y = np.dot(Q.T, B)
X_qr = np.linalg.solve(R, Y)

print("Задача 3: Решение системы методом QR-разложения")
print("Решение X:\n", X_qr)
print("Проверка решения (AX):\n", np.dot(A, X_qr))
print("Решение через np.linalg.solve:\n", np.linalg.solve(A, B))

Задача 3: Решение системы методом QR-разложения
Решение X:
 [ 0.34261045  0.44394439  0.17387099 -0.82822646]
Проверка решения (AX):
 [-8.4  4.5  3.3 14.3]
Решение через np.linalg.solve:
 [ 0.34261045  0.44394439  0.17387099 -0.82822646]


In [7]:
# Задача 4: Решение методом простых итераций
def simple_iterations(A, B, tol=1e-3, max_iter=100):
    n = len(B)
    X = np.zeros(n)
    table = []
    
    for iteration in range(max_iter):
        X_new = np.zeros(n)
        for i in range(n):
            s = sum(A[i, j] * X[j] for j in range(n) if i != j)
            X_new[i] = (B[i] - s) / A[i, i]
        
        table.append(X_new.copy())
        
        if np.linalg.norm(X_new - X, ord=np.inf) < tol:
            break
        X = X_new
    
    df = pd.DataFrame(table, columns=[f"x{i+1}" for i in range(n)], index=[f"Iter {i+1}" for i in range(len(table))])
    return X_new, df

In [12]:
A = np.array([
    [2.7, 3.3, 1.3],
    [3.5, -1.7, 2.8],
    [4.1, 5.8, -1.7]
])
B = np.array([2.1, 1.7, 0.8])
M_1_N = np.array([[49, 8, -2],
                  [-8, 50, -15],
                  [36, 0, -45]])
g = np.array([4, 4, -30])
X_iter, iteration_table = simple_iterations(M_1_N, g)

print("Задача 4: Решение методом простых итераций")
print("Таблица итераций:\n", iteration_table)
print("Проверка решения (AX):\n", np.dot(A, X_iter))
print("Решение через np.linalg.solve:\n", np.linalg.solve(A, B))
print(np.dot(A, np.linalg.solve(A, B)))

Задача 4: Решение методом простых итераций
Таблица итераций:
               x1        x2        x3
Iter 1  0.081633  0.080000  0.666667
Iter 2  0.095782  0.293061  0.731973
Iter 3  0.063662  0.314917  0.743293
Iter 4  0.060556  0.313174  0.717597
Iter 5  0.059792  0.304968  0.715112
Iter 6  0.061030  0.304100  0.714500
Iter 7  0.061147  0.304115  0.715491
Проверка решения (AX):
 [2.09881388 1.70039321 0.79823432]
Решение через np.linalg.solve:
 [0.06113307 0.30445323 0.71557312]
[2.1 1.7 0.8]


In [9]:
# Задача 5: Найти псевдорешение системы
A = np.array([
        [3.1, 2.8, 1.9],
        [1.9, 3.1, 2.1],
        [7.5, 3.8, 4.8],
        [3.01, -0.33, 0.11]
    ])
B = np.array([0.2, 2.1, 5.6, 0.13])    
X_pseudo = np.linalg.lstsq(A, B, rcond=None)[0]
   
print("Задача 5: Псевдорешение системы")
print("Псевдорешение X:\n", X_pseudo)

Задача 5: Псевдорешение системы
Псевдорешение X:
 [-0.28402623 -1.02866072  2.43639639]
