In [2]:
import numpy as np
import pandas as pd
from scipy.linalg import lu

In [3]:
A = np.tril(np.random.rand(5, 5) * 10)  # Нижнетреугольная матрица
B = np.random.rand(5) * 10  # Вектор B
X = np.linalg.solve(A, B)

print("Задача 1: Решение системы AX = B с нижнетреугольной матрицей")
print("Матрица A:\n", A)
print("Вектор B:\n", B)
print("Решение X:\n", X)

Задача 1: Решение системы AX = B с нижнетреугольной матрицей
Матрица A:
 [[1.20323032 0.         0.         0.         0.        ]
 [4.04076632 8.25105647 0.         0.         0.        ]
 [3.35584709 4.89623188 5.90485875 0.         0.        ]
 [5.75820682 5.23008516 2.90692036 1.19769238 0.        ]
 [1.95603644 7.0026782  6.09370189 1.255974   9.76944583]]
Вектор B:
 [7.01813608 0.13922866 9.17598056 8.46641486 3.62596472]
Решение X:
 [  5.83274536  -2.83957969   0.59365003 -10.01441542   2.15589343]


In [4]:
A = np.array([
    [8.2, -3.2, 14.2, 14.8],
    [5.6, -12, 15, -6.4],
    [5.7, 3.6, -12.4, -2.3],
    [6.8, 13.2, -6.3, -8.7]
])
B = np.array([-8.4, 4.5, 3.3, 14.3])
    
P, L, U = lu(A)
Y = np.linalg.solve(L, np.dot(P, B))
X = np.linalg.solve(U, Y)
    
print("Задача 2: Решение системы методом LU-разложения")
print("Решение X:\n", X)

Задача 2: Решение системы методом LU-разложения
Решение X:
 [ 0.34261045  0.44394439  0.17387099 -0.82822646]


In [5]:
# Задача 3: Решение системы QR-разложением методом Грама-Шмидта
def gramschmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R

In [6]:
A = np.array([
    [8.2, -3.2, 14.2, 14.8],
    [5.6, -12, 15, -6.4],
    [5.7, 3.6, -12.4, -2.3],
    [6.8, 13.2, -6.3, -8.7]
])
B = np.array([-8.4, 4.5, 3.3, 14.3])
Q, R = gramschmidt(A)
Y = np.dot(Q.T, B)
X_qr = np.linalg.solve(R, Y)

print("Задача 3: Решение системы методом QR-разложения")
print("Решение X:\n", X_qr)
print("Проверка решения (AX):\n", np.dot(A, X_qr))
print("Решение через np.linalg.solve:\n", np.linalg.solve(A, B))

Задача 3: Решение системы методом QR-разложения
Решение X:
 [ 0.34261045  0.44394439  0.17387099 -0.82822646]
Проверка решения (AX):
 [-8.4  4.5  3.3 14.3]
Решение через np.linalg.solve:
 [ 0.34261045  0.44394439  0.17387099 -0.82822646]


In [7]:
# Задача 4: Решение методом простых итераций
def simple_iterations(A, B, tol=1e-3, max_iter=100):
    n = len(B)
    X = np.zeros(n)
    table = []
    
    for iteration in range(max_iter):
        X_new = np.zeros(n)
        for i in range(n):
            s = sum(A[i, j] * X[j] for j in range(n) if i != j)
            X_new[i] = (B[i] - s) / A[i, i]
        
        table.append(X_new.copy())
        
        if np.linalg.norm(X_new - X, ord=np.inf) < tol:
            break
        X = X_new
    
    df = pd.DataFrame(table, columns=[f"x{i+1}" for i in range(n)], index=[f"Iter {i+1}" for i in range(len(table))])
    return X_new, df

In [21]:
A = np.array([
    [2.7, 3.3, 1.3],
    [3.5, -1.7, 2.8],
    [4.1, 5.8, -1.7]
])
B = np.array([2.1, 1.7, 0.8])
A_dif = np.array([[6.2,-1.6,4.1],
                  [0.8, -5, 1.5],
                  [1.3, 0.8, 4.3]])
B_dif = np.array([3.8, -0.4, 3.4])
X_iter, iteration_table = simple_iterations(A_dif, B_dif)

print("Задача 4: Решение методом простых итераций")
print("Таблица итераций:\n", iteration_table)
print("Проверка решения (AX):\n", np.dot(A_dif, X_iter))
print("Решение через np.linalg.solve:\n", np.linalg.solve(A, B))
print(np.dot(A, np.linalg.solve(A, B)))

Задача 4: Решение методом простых итераций
Таблица итераций:
                x1        x2        x3
Iter 1   0.612903  0.080000  0.790698
Iter 2   0.110668  0.415274  0.590518
Iter 3   0.329567  0.274862  0.679980
Iter 4   0.234171  0.336725  0.639924
Iter 5   0.276624  0.309445  0.657255
Iter 6   0.258123  0.321436  0.649496
Iter 7   0.266349  0.316149  0.652858
Iter 8   0.262761  0.318473  0.651355
Iter 9   0.264355  0.317448  0.652007
Iter 10  0.263659  0.317899  0.651716
Проверка решения (AX):
 [ 3.79808503 -0.40099345  3.39945597]
Решение через np.linalg.solve:
 [0.06113307 0.30445323 0.71557312]
[2.1 1.7 0.8]


In [10]:
# Задача 5: Найти псевдорешение системы
A = np.array([
        [3.1, 2.8, 1.9],
        [1.9, 3.1, 2.1],
        [7.5, 3.8, 4.8],
        [3.01, -0.33, 0.11]
    ])
B = np.array([0.2, 2.1, 5.6, 0.13])    
X_pseudo = np.linalg.lstsq(A, B, rcond=None)[0]
   
print("Задача 5: Псевдорешение системы")
print("Псевдорешение X:\n", X_pseudo)

Задача 5: Псевдорешение системы
Псевдорешение X:
 [-0.28402623 -1.02866072  2.43639639]
